name: Lint Commit Messages
on:
  pull_request:
    branches:
      - local_build
  push:
    branches:
      - local_build

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
